/**
 * This file is generated by @wfh/tool-misc
 */
import {config, PackageSettingInterf} from '@wfh/plink';

/**
 * Package setting type
 */
export interface $__Foobar__$Setting {
  /** Description of config property */
  disabled: boolean;
}

/**
 * Plink runs this funtion to get package level setting value,
 * function name "defaultSetting" must be also configured in package.json file
 */
export const defaultSetting: PackageSettingInterf<$__Foobar__$Setting> = function(cliOptions) {
  const defaultValue: $__Foobar__$Setting = {
    disabled: false
  };
  // Return settings based on command line option "dev"
  if (cliOptions.dev) {
    defaultValue.disabled = true;
  }

  const env = cliOptions.env;
  // Return settings based on command line option "env"
  if (env === 'local') {
    defaultValue.disabled = true;
  }

  return defaultValue;
};

/** For Node.js runtime, replace module in "require()" or import syntax */
defaultSetting.setupNodeInjector = function(factory, allSetting) {
  // factory.fromPackage('@wfh/foobar').alias('moduleA', 'moduleB');
};
/** For Client framework build tool (React, Angular), replace module in "require()" or import syntax */
defaultSetting.setupWebInjector = function(factory, allSetting) {
  // factory.fromPackage('@wfh/foobar').alias('moduleA', 'moduleB');
};


/**
 * The return setting value is merged with files specified by command line options "--prop" and "-c"
 * @return setting of current package
 */
export function getSetting() {
  /* eslint-disable dot-notation,@typescript-eslint/dot-notation */
  return config()['$__foobarPackage__$'];
}
