/**
 * This file is generated by @wfh/tool-misc
 */
import {config, PackageSettingInterf} from '@wfh/plink';

/**
 * Package setting type
 */
export interface MarkdownBaseSetting {
  markdownDevServer?: string;
}

/**
 * Plink runs this funtion to get package level setting value,
 * function name "defaultSetting" must be also configured in package.json file
 */
export const defaultSetting: PackageSettingInterf<MarkdownBaseSetting> = function(_cliOptions) {
  const defaultValue: MarkdownBaseSetting = {
  };
  // Return settings based on command line option "dev"
  // if (cliOptions.dev) {
  // }

  // const env = cliOptions.env;
  // Return settings based on command line option "env"
  // if (env === 'local') {
  // }

  return defaultValue;
};

/** For Node.js runtime, replace module in "require()" or import syntax */
defaultSetting.setupNodeInjector = function(factory, allSetting) {
  // factory.fromPackage('@wfh/foobar').alias('moduleA', 'moduleB');
};
/** For Client framework build tool (React, Angular), replace module in "require()" or import syntax */
defaultSetting.setupWebInjector = function(factory, allSetting) {
  // factory.fromPackage('@wfh/foobar').alias('moduleA', 'moduleB');
};


/**
 * The return setting value is merged with files specified by command line options "--prop" and "-c"
 * @return setting of current package
 */
export function getSetting() {
  /* eslint-disable dot-notation,@typescript-eslint/dot-notation */
  return config()['@wfh/markdown-base'];
}
