/**
 * This file is generated by @wfh/tool-misc
 */
import {config, PackageSettingInterf} from '@wfh/plink';

/**
 * Package setting type
 */
export interface MaterialComponentsReactSetting {
  /** Theme of Material design */
  materialTheme: 'default' | 'ugly';
}

/**
 * Plink runs this funtion to get package level setting value,
 * function name "defaultSetting" must be also configured in package.json file
 */
export const defaultSetting: PackageSettingInterf<MaterialComponentsReactSetting> = function(cliOptions) {
  const defaultValue: MaterialComponentsReactSetting = {
    materialTheme: 'default'
  };

  return defaultValue;
};

/** For Node.js runtime, replace module in "require()" or import syntax */
defaultSetting.setupNodeInjector = function(factory, allSetting) {
  // factory.fromPackage('@wfh/foobar').alias('moduleA', 'moduleB');
};
/** For Client framework build tool (React, Angular), replace module in "require()" or import syntax */
defaultSetting.setupWebInjector = function(factory, allSetting) {
  // factory.fromPackage('@wfh/foobar').alias('moduleA', 'moduleB');
};


/**
 * The return setting value is merged with files specified by command line options "--prop" and "-c"
 * @return setting of current package
 */
export function getSetting() {
  /* eslint-disable dot-notation,@typescript-eslint/dot-notation */
  return config()['@wfh/material-components-react'];
}
