/**
 * This file's content will be dynamically replaced by the content generated by ../ts/ng-ts-replace.ts
 * during compilation time
 */

export default function handleBootStrap(module: any, bootstrap: ()=> Promise<any>) {
	document.addEventListener('DOMContentLoaded', () => {
		// Wait for Server side rendering state element being loaded on HTML.
		// handleBootStrap placeholder
		(window as any).__DOMContentLoaded = true;
	});
	if ((window as any).__DOMContentLoaded) {
		// When hot module replacement triggere this file being executed,
		// we don't need to wait for DOMContentLoaded event anymore.
		// handleBootStrap placeholder
	}
}
