/**
 * This file's content will be dynamically replaced by the content generated by ../ts/ng-ts-replace.ts
 * during compilation time
 */

export default function handleBootStrap(module: any, bootstrap: ()=> Promise<any>) {
	// handleBootStrap placeholder
}
